### ISSUE TITLE
Add static rendering

### ISSUE THREAD

**Issue by gunzip** [rocjs/roc-package-web-app-react#14]
As seen on https://github.com/vgno/roc-web-react/issues/22

> We should add the possibility to render sites to static markup. This can be used with Github Pages and running applications in general without the need for a node backend.

which couples with "make react-router configurable", expecially the history params: browserHistory (which depends from server) vs hashHistory (which is client only).

**Comment by dlmr** [comment]
This issue has been moved into the mono repository https://github.com/rocjs/extensions/issues/19.
