### ISSUE TITLE
How can I move some code into a package?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#22]
Hi,

I would like to move some components out of my app and into a separate package. However, if I do this, I will lose all the benefits of `roc` for my package because the package will have to have its own build system and biolerplate. Is there a way to solve this today?

Thanks,
Wadim

**Comment by dlmr** [comment]
Do you mean that you want to create a standalone component that can for instance be published to npm and also be used inside you application that is built with Roc?

**Comment by wadim** [comment]
Yes, in my app I have a growing collection of components. Some of them are highly reusable and I would like to use them in other apps. I would like to publish them to npm and when I'm building my next app, I would like to just `npm install` my reusable components and and be able to import them. This already works obviously.

The problem is that I need to define a build system for my component packages and deal with a lot of boilerplace. I was wondering if I could use `roc` to build my component packages instead so that I get a build system and the boilerplate is kept to a minimum.

Another problem, but this one is a bit unrelated to roc itself and a bit less important, is that if my components are in a separate package then I have to transpile them to es5 and use the transpiled version in my app which is bad because I can't do tree-shaking. Am I right?

**Comment by wadim** [comment]
I guess what I am saying is that I would like to have my components in separate packages so they can be `import`ed into other apps but when I include them into a Roc app I would like them to behave as if they were a part of the app and not a separate package. I would like them to:
- rely on the build system of the Roc app
- be read as ES6 so tree-shaking can take place

It's highly probable that this is just wishful thinking though.

**Comment by dlmr** [comment]
> The problem is that I need to define a build system for my component packages and deal with a lot of boilerplace. I was wondering if I could use roc to build my component packages instead so that I get a build system and the boilerplate is kept to a minimum.

Yes this is possible today and will be even better in the near future. Soon you will be able to use [`roc-package-web-component-react`](https://github.com/rocjs/roc-package-web-component-react) that will take care of all boilerplate and provide the best possible development experience. In the mean time you can use a combination of  [`roc-package-web-component`](https://github.com/rocjs/roc-package-web-component) and [`roc-plugin-react`](https://github.com/rocjs/roc-plugin-react).

> Another problem, but this one is a bit unrelated to roc itself and a bit less important, is that if my components are in a separate package then I have to transpile them to es5 and use the transpiled version in my app which is bad because I can't do tree-shaking. Am I right?

When using `roc-package-web-component` (or a variant of it) you will get the option to build to CommonJS (ES5), ES2015 module syntax and UMD. So tree-shaking will be possible. This is how your `package.json` would look:

``` json
{
  ...
  "main": "build/es5/index.js",
  "jsnext:main": "build/es6/index.js",
  ...
}
```

> I guess what I am saying is that I would like to have my components in separate packages so they can be imported into other apps but when I include them into a Roc app I would like them to behave as if they were a part of the app and not a separate package.

This is possible to do and would be similar to how packages inside Roc works today. That is a type of Roc components or `roc-component` perhaps. It's something we have talked about supporting but we have not started working on this yet. So you can already today get the benefits of tree-shaking but more specific optimizations will be harder to do.

**Comment by wadim** [comment]
Great! Thanks! Did I understand you correctly that I can use a combination of `roc-package-web-component` and `roc-plugin-react` already today?

How can I make this happen? What do I need to do in my component package to use these (or to `roc`ify it)?

**Comment by dlmr** [comment]
Yes, you can use that today. `roc-package-web-component` is heavily used already and it should in theory be possible to combine it with the `roc-react-plugin` as is done in `roc-package-web-app-react`.

A good start is to install the following in the component project:

``` bash
npm install roc-package-web-component-dev roc-plugin-react-dev --save-dev
```

Then you will most likley create a simple demo file (this will be taken care by the `roc-package-web-component-react` in the future) and use the demo file in `dev`. A custom template file is also probably needed.

Try out this in the project, might work for you.

**templates/index.html**

``` html
<!DOCTYPE html>
<html>
  <head>
        <meta charset="utf-8">
        <title>{{ projectName }} - Development</title>
    </head>
    <body>
        <div id="roc-component"></div>
        <script src="{{ bundlePath }}"></script>
    </body>
</html>
```

**demo/index.js**

``` javascript
import React from 'react';
import { render } from 'react-dom';
import DemoComponent from '../src/index.js';

render(<DemoComponent />, document.getElementById('roc-component'));
```

**Start in development**

``` bash
roc dev --build-name myComponent --dev-template-path templates --build-input-web demo/index.js
```

**Build for publishing**

``` bash
roc build
```

**Comment by wadim** [comment]
Do I need to run `roc init` or create some sort of config file? Roc doesn't seem to understand `build` at the moment.

**Comment by dlmr** [comment]
It should be enough if the mentioned extensions above have been installed.

**Comment by wadim** [comment]
What am I missing here?

```
$ npm install roc-package-web-component roc-plugin-react roc-plugin-react-dev
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> spawn-sync@1.0.15 postinstall /Users/wadim/components/node_modules/spawn-sync
> node postinstall


> roc@1.0.0-rc.10 postinstall /Users/wadim/components/node_modules/roc
> node ./scripts/post-install.js

components@1.0.0 /Users/wadim/components
├── roc-package-web-component@1.0.0-alpha.3  extraneous
├─┬ roc-plugin-react@1.0.0-alpha.2 
│ ├── react@15.0.2 
│ └── react-dom@15.0.2 
└── roc-plugin-react-dev@1.0.0-alpha.2  extraneous

npm WARN components@1.0.0 No repository field.
Wadims-MacBook-Pro:components wadim$ roc build
Found a local version of Roc, will use that over the global one. 

(node:19589) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
  Error    Invalid Command

  Did not understand build - Did you mean init
```

**Comment by dlmr** [comment]
Woops, my bad.

You need to install `roc-package-web-component-dev`, you actually do not need anything other than the dev versions here. So more correctly:

``` bash
npm install roc-package-web-component-dev roc-plugin-react-dev --save-dev
```

**Comment by wadim** [comment]
Hmmm... it seems I still get the same error message with the two `-dev` packages

```
Did not understand build - Did you mean init
```

**Comment by dlmr** [comment]
They need to be listed in the `package.json` for Roc to detect them, could that be the problem?

**Comment by wadim** [comment]
Ah, that must be it!

**Comment by wadim** [comment]
Ok! We have progress! But now there's another error:

```
$ roc build
Found a local version of Roc, will use that over the global one. 

(node:19802) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
  Error    Validation Problem

  Configuration was not valid.

  Validation failed for field name - Received: [Nothing]. A value was required but none was given!
```

**Comment by wadim** [comment]
Specifying `--build-name myComponent` parameter to `roc build` helped with that.

**Comment by dlmr** [comment]
I have done some tests locally and you will need to create a `.babelrc` file in your project and add `babel-preset-react`. All of this will be managed eventually by a package.

**Comment by wadim** [comment]
I did that but it seems `es5` and `es6` contain exactly the same content — both contain ES5 code.

**Comment by dlmr** [comment]
I have now created a working example.

https://github.com/dlmr/roc-react-component-example

In this example the code is correctly built to ES5 and ES6. The only difference is that the ES6 build will still have `exports` and `imports`, everything else will be transpiled.

**Comment by wadim** [comment]
Yes, that was my mistake. I had one preset too many, namely `es2015`. Removing it solved the problem. Thanks a lot for the help Gustav! I'm always amazed by the how quick and precise your replies are. Thanks again!
