### ISSUE TITLE
Better handling of non existing reducers-file

### ISSUE THREAD

**Issue by Naycon** [rocjs/roc-package-web-app-react#25]
If one accidentally specifies a path for the `reducers` setting that doesn't exist, e.g:

```
build: {
      reducers: 'src/i/dont/exist.js',
      routes: 'src/routes/index.js',
}
```

...the resulting error message is confusing and doesn't help very much in letting you know what is wrong:

```
roc:react-render Fetching error +247ms   Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(AddTodoImpl)". Either wrap the root component in a <Provider>  , or explicitly pass "store" as a prop to "Connect(AddTodoImpl)".
```

It would be great if this package (or Roc) could instead point out that file couldn't be found at all.

**Comment by dlmr** [comment]
The thing to think about when implementing this is to only warn when a custom path has been provided, since we want it to fail silently when the default path can't be resolved.

**Comment by dlmr** [comment]
This issue has been moved into the mono repository rocjs/extensions#20.
