### ISSUE TITLE
Minimize client build?

### ISSUE THREAD

**Issue by jimzezz** [rocjs/roc-package-web-app-react#32]
Hello!

I was looking through the source how react router's history is created and noticed that the full bundle from history.is is included in the client app. Is there a particular reason for that instead of importing just `history/lib/createBrowserHistory` like [history.js recommends](https://github.com/mjackson/history/blob/v2.x/docs/GettingStarted.md#minimizing-your-build)?

**Comment by dlmr** [comment]
Hi!

I do not think there is any reason for this, seems like it just is a mistake and a PR that corrects this is very appreciated! 👍
