### ISSUE TITLE
Determine strategy to provide Babel-polyfill for older browsers

### ISSUE THREAD

**Issue by pierluigi** [rocjs/roc-package-web-app-react#42]
Older browsers require the `babel-polyfill` https://babeljs.io/docs/usage/polyfill/ – do you think it's this package's responsibility to solve this issue?

**Comment by dlmr** [comment]
This is definitely something that should be managed by Roc and this package is a good place. 

We just need to do this correctly when adding this, a reason for us not adding it as of yet. What I mean with that we would optimally load polyfills on demand in clients that require them to avoid increasing the size in modern browsers. 

There are several strategies on how to solve this some of which are mentioned in this article https://philipwalton.com/articles/loading-polyfills-only-when-needed. We could probably using the knowledge that Roc have about the application only add the needed checks needed to polyfill what is needed by the specific application. 

On this topic we should also look into what we transpile using Babel and target the correct browsers, we can do this using https://github.com/babel/babel-preset-env potentially.

**Comment by wadim** [comment]
Before we figure out a generic polyfill strategy for roc, what is the best way to include `babel-polyfill` in individual projects for now?

**Comment by dlmr** [comment]
The current suggested way is the following.

### `roc.config.js`

``` js
module.exports = {
  /* … */
  settings: {
    /* … */
    build: {
      /* … */
      resources: ['src/polyfill.js'],
    },
  },
};
```

### `src/polyfill.js`

``` js
if (__WEB__) {
  require('babel-polyfill');
}
```

**Comment by dlmr** [comment]
This issue has been moved into the mono repository rocjs/extensions#21.
