### ISSUE TITLE
Support custom handling of errors when React fails to render correctly on the server

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc-package-web-app-react#49]
## Problem
We should add a way to manage generic errors that happen on the server and where React is the culprit in one way or another. The current behaviour is that we render the template without anything in the application `div`, meaning that the client can pick up potentially, however it will most likely fail as well if the server did not manage to render correctly. 

The problem can be divided up into two parts:
- React Router fails to find a matching route.
- The rendering of the application using React fails for some reason.

[The code corresponding to this can be seen here.](https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react/src/app/server/reactRenderer.js#L91-L103)

The first part is possible to manage using `react-router` and `react-server-status` but we should still provide a way to manage this outside this, because it can be caused by a bug somewhere.

The question is how we should approach this in a generic way that fits into how Roc does it. 

## Suggestion
The suggestion is that we give the templating system we are using more power allowing for more than a single template file along with access to the information we have.

| Template file | Extra values | Old file |
| ---- | ----- | ---- |
| `default.html` |  | `main.html` |
| `404.html` | | |
| `500.html` | `error` | |

This means that we will use the:
- `404.html` template when we do not have any `renderProps`.
- `500.html` template when we got an `error`.
- `default.html` template when everything went fine or if no custom `404.html` and `500.html` templates have been defined.

Roc should probably provide simple default templates for all cases. Both `404.html` and `500.html` should probably have `<div id="application"></div>` so that the React code can mount on the client side if it was a server specific error, or should we not do this?

__Pseudo code__
```js
if (error) {
  return resolve({
    status: 500,
    body: renderPage('500.html' || 'default.html', error),
  });
} else if (!renderProps) {
  return resolve({
    status: 404,
    body: renderPage('404.html' || 'default.html'),
  });
}
// Render normally
renderPage('default.html');
```

We also probably want to default to look for templates in a predefined location, something we do not do today. My suggestion is to use `templates/` in the root of the project for this with the possibility to override it. _Currently `views/` are often used but feels like `templates/` seems more fitting._

## Stability
The suggestion approach will be breaking for projects that have created their own template but have only defined the `runtime.template.path` but not the `runtime.template.name`.

**Comment by dlmr** [comment]
## Suggestion

Another alternativ is to use the same template but provide a variable that can be used to conditionally rendering it in different ways.

``` jinja
{% if status == 500 %}
  Woops!
{% elif status == 404 %}
  Not found…
{% else %}
  Everything is fine! 🎉
{% endif %}
```

## Stability

This would not change anything more than introduce new functionality, hence it is not breaking.

**Comment by andreasrs** [comment]
I really like the approach outlined here, and from the top of my head I think it would cover all common scenarios in a user-friendly way.

About 1 template vs multiple... In this case I lean toward having a single template that can handle everything conditionally. It just seems more flexible long-term to me instead of having a file-per-scenario.

## 

:+1: to overall proposal, my preference is to have a single (overridable) template that is open to conditional behaviour.

**Comment by dlmr** [comment]
We probably also want a way to manage internationalisation on errors. 

One way of doing this is to give access to the `this.request` from Koa in the template rendering making it possible to get the language and do something conditionally based on it.

Could look something like this in the template.

``` jinja
{% if request.acceptsLanguages('sv') %}
  {% include "swedish.html" %}
{% elif request.acceptsLanguages('fr') %}
  {% include "french.html" %}
{% else %}
  {% include "default.html" %}
{% endif %}
```
