### ISSUE TITLE
requiring external css and js

### ISSUE THREAD

**Issue by aeldaly** [rocjs/roc-package-web-app-react#50]
I'd like to use this https://github.com/danawoodman/react-fontawesome as an example.

How do I include font-awesome JS and CSS into the project?

**Comment by dlmr** [comment]
Hi!

The easiest way of doing that is by using [React Helmet](https://github.com/nfl/react-helmet) that you will have access to by default in your project. However, there is currently [a bug in it that can create problems when including JavaScript and using server side rendering](https://github.com/nfl/react-helmet/issues/149) (something that we are doing by default in Roc).

I would therefore instead recommending to take ownership over the template file and do it the old fashioned way. See https://github.com/rocjs/roc/issues/122#issuecomment-254490061 for how to do this.
