### ISSUE TITLE
Default favicon

### ISSUE THREAD

**Issue by sgulseth** [rocjs/roc-package-web-app-react#58]
The roc.config provided with this extension(https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react/src/config/roc.config.js#L14-L17) has a default favicon.png. If only setting helmet-head resources through the React-component you end up with two favicons:

<img width="1637" alt="screenshot 2016-12-24 15 39 54" src="https://cloud.githubusercontent.com/assets/1627633/21467462/43c7d73a-c9ef-11e6-91e9-d1ec361e3528.png">

Helmet-component:
```
<Helmet
                    link={[
                        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Montserrat' },
                        { rel: 'stylesheet', href: '/css/loaders.css' },
                        { rel: 'icon', href: '/img/favicon.png' }
                    ]}
                />
```

Temp fix is to manually override settings.runtime.head.link

**Comment by dlmr** [comment]
Thanks for the report! We had good intentions with this default in the configuration, pushing for convention over configuration, but seems it might be best to remove it to avoid this problem since we have seen this before.  

We could also check so only a single `icon` is used but that is probably complexity that gives little value.

**Comment by sgulseth** [comment]
I see. Wouldn't it be "enough convention" by providing the favicon setup through the bootstraping?

**Comment by dlmr** [comment]
I think that would probably be best yes. A PR that changes this would be appreciated. 🙂 

We will also need to update our templates to match this change.

**Comment by dlmr** [comment]
This issue has been moved into the mono repository rocjs/extensions#22.
