### ISSUE TITLE
Add support for `export * from '...'` syntax

### ISSUE THREAD

**Issue by pierluigi** [rocjs/roc-package-web-app-react#60]
It should be possible to use the `export * from` syntax, however currently this ends up in a 
```
Module parse failed: /.../node_modules/babel-loader/lib/index.js? [omitted] 
Line 3: Unexpected token
You may need an appropriate loader to handle this file type.
| 'use strict';
|
| import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
| import _Object$keys from 'babel-runtime/core-js/object/keys';
| Object.defineProperty(exports, "__esModule", {
 @ ./src/override/default/get-routes-and-store.js 49:71-94
```

sort of error.

This is probably linked to this Babel issue https://github.com/babel/babel/issues/2877 but there maybe some workarounds we can use in the meantime to make this work in Roc.

**Comment by dlmr** [comment]
This will be solved in a new version of Babel, will close this issue and if not we will revisit it in https://github.com/rocjs/extensions.
