### ISSUE TITLE
[roc-package-web-app-react-dev] Compatibility issue with IE 9 / 10

### ISSUE THREAD

**Issue by jon301** [rocjs/roc-package-web-app-react#62]
Hi,

The package `yellowbox-react` (used to display yellow warnings in the bottom of the page in dev environment) is a dependency of `roc-package-web-app-react-dev` :

```
/home/jonjon/work/project
└─┬ roc-package-web-app-react-dev@1.0.0-beta.9
  └── yellowbox-react@0.9.4
```

However `yellowbox-react` is not compatible with IE 9 & 10 as it uses ES6 [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility) : https://github.com/iamdustan/yellowbox-react/blob/master/src/common.js#L6

This results of the following error : 

```
SCRIPT5009: 'Map' is undefined
```

How can we fix this ?

Thanks for your help !

Jon

**Comment by dlmr** [comment]
You can disable by setting `dev.yellowbox.ignore` to `false`. See if that works!

**Comment by jon301** [comment]
Thanks ! I disabled the plugin with `dev.yellowbox.enabled` to `false`

https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react-dev/src/config/roc.config.meta.js#L148

**Comment by dlmr** [comment]
Right, my bad naming the wrong setting! 😅
