### ISSUE TITLE
Eslint not installed by default?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#72]
I created a new app from scratch with the `web-app-react` template. I can see that `eslint` is not installed. Is that on purpose?

**Comment by dlmr** [comment]
That is not intended and should be fixed, thanks for reporting it!

We have a work in progress version that you can try out that is a little better than the default one, although not complete.

```
roc init web-app-react wip
```

**Comment by dlmr** [comment]
This has been addressed.
