### ISSUE TITLE
How to get a request header into a server-side rendered react component?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#75]
I need to provide the value of the 'User-Agent' request header to a component which is rendered server-side. I assume I must get this information from `koa` and, specifically, the `koa` instance which `roc` uses. Any quick pointers would be highly appreciated.

**Comment by dlmr** [comment]
The default way to do this is to use a Koa middleware that adds this to the Redux state that then can be consumed by the React.

[Simple example here.](https://github.com/rocjs/roc-package-web-app-react/blob/master/examples/complex/src/koa-middlewares.js#L19-L33)

Do you think this would work?

**Comment by wadim** [comment]
This will work just fine. Thanks!
