### ISSUE TITLE
how to configure for non-ssr

### ISSUE THREAD

**Issue by pkrogel-kws** [rocjs/roc-package-web-app-react#77]
All of our React applications are used internally and have no real need for server side rendering--we'd rather just avoid jumping through those hoops all together. Can I get some direction on how to go about setting up webpack-dev-server with Roc, or even just disabling Koa SSR?

I'd imagine adding this as an example or documentation might help others without a need for SSR get started with Roc. Thanks!

**Comment by dlmr** [comment]
During development it should be fine to run the setup as is together with using `settings.runtime.ssr = false`, this will only use the Koa part as a development server but run the application client side only.

For running in production we need to do a little more work, and currently manual work until we complete and merge #64. [See this workaround until we have that feature in place for guidance.](https://gist.github.com/dlmr/ceecfa8c8d25e8f20d012bd1f7c782e4)
