### ISSUE TITLE
Make store available as global variable when developing

### ISSUE THREAD

**Issue by Alxandr** [rocjs/roc-package-web-app-react#79]
Sometimes it's necessary to inspect/modify the redux-store from the browser console. This is today only possible if you have the react extension installed (in chrome at least), and then select the provider node and do `$r.props.store`. It would be nice if the `roc-package-web-app-react` plugin did something akin to:

```js
if (__DEV__) {
  global['__REDUX_STORE__'] = store;
}
```

**Comment by dlmr** [comment]
I'm afraid if we do this by default it might result in some developers relaying on this "functionality" during development, making their applications break when taking it into production.

I would be more comfortable if this was something that each individual project did themselves based on their needs, like adding it to `componentDidMount` in their main React component using the same pattern as suggested here which is possible today.

Another solution to potentially achieve something similar to exposing it globally is to use https://github.com/zalmoxisus/redux-devtools-extension that is supported out of the box in development as well as a local instance of Redux Devtools (CTRL-H).
