### ISSUE TITLE
How to inline styles and preserve SSR?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#83]
Hi,

I am considering inlining styles in the HTML of my app.

I know it can be done by employing `html-webpack-plugin` and supplying own template (as described here https://gist.github.com/dlmr/ceecfa8c8d25e8f20d012bd1f7c782e4) but then I would lose the SSR capability and actually omit roc's templating system entirely.

Is it possible to inline styles without sacrificing functionality? Any pointers would be appreciated.

**Comment by dlmr** [comment]
Hello!

When you talk about inline styles, do you mean adding critical CSS to the head of the document in a `<style>` tag?

**Comment by wadim** [comment]
Yes. I mean adding critical CSS to the head of the document in a '<style>' tag.

**Comment by dlmr** [comment]
You can extend the template system used by Roc and add CSS to a `<style>` tag, either manually or generating it through your build in some way. Which of these are you aiming to use, manually adding CSS or using some library that does this?

**Comment by wadim** [comment]
I would definitely like the extraction of the CSS to be automatic. For now I just want all my CSS to be inlined. In the future I would like to use a tool which extracts critical CSS for me automatically.

**Comment by dlmr** [comment]
You can do it similar to how it's done here.

https://gist.github.com/dlmr/8512b5172a3345866749124e9d661103

This will be a little easier in the future, will get back to you when we have the latest stuff landed.
