### ISSUE TITLE
roc build in production tries to load dev dependency

### ISSUE THREAD

**Issue by Visya** [rocjs/roc-package-web-app-react#85]
Hi,

I am trying to build an application with `NODE_ENV=production` but get an error
``` bash
$ roc build -b -V
Found a local version of Roc, will use that over the global one.

  Warning    Roc Extension Loading Failed

  Failed to load Roc package named roc-package-web-app-react-dev.
  Make sure you have it installed. Try running: npm install --save roc-package-web-app-react-dev

  Error: Cannot find module roc-package-web-app-react-dev
      at getExtension
  [..]

  Info    Extensions Used

  roc-package-web-app-react - 1.0.0
  roc-plugin-assets-images - 1.0.0
  roc-plugin-style-css - 1.0.0
  roc-plugin-style-sass - 1.0.0

  Info    Extensions Tree

  app@1.0.0
  ├─┬ roc-package-web-app-react@1.0.0
  │ ├─┬ roc-package-web-app@1.0.0
  │ │ ├─┬ roc-package-webpack-node@1.0.0
  │ │ │ ├─┬ roc-package-webpack@1.0.0
  │ │ │ │ └── roc-abstract-package-base@1.0.0
  │ │ │ └── roc-plugin-start@1.0.0
  │ │ └─┬ roc-package-webpack-web@1.0.0
  │ │   └─┬ roc-package-webpack@1.0.0
  │ │     └── roc-abstract-package-base@1.0.0
  │ └── roc-plugin-react@1.0.0
  ├── roc-plugin-assets-images@1.0.0
  ├── roc-plugin-style-css@1.0.0
  └── roc-plugin-style-sass@1.0.0

  Warning    Configuration

  Could not find the configuration file at $CORRECT_PATH_TO_DIR/roc.config.js.

  Error    Invalid command

  Did not understand build - Did you mean init
```

I have `roc-package-web-app-react` required in the client and server index files. The config file is in place, so no idea why the warning shows up. `roc.config.js` is:
``` js
var IgnorePlugin = require('webpack').IgnorePlugin;

module.exports = {
    settings: {
        runtime: {
            applicationName: 'App',
            port: 3030,
            serve: ['public', 'build/client'],
            configWhitelistProperty: 'client',
            koa: {
                lowercase: {
                    enabled: false,
                },
                trailingSlashes: {
                    enabled: false,
                },
                staticServe: {
                    maxage: 60 * 60 * 24 * 1000, // 24 hours, in milliseconds
                },
            },
            template: {
                path: 'views',
            },
        },
        build: {
            reducers: 'src/shared/redux/reducers.js',
            routes: 'src/shared/routes/index.js',
            koaMiddlewares: 'src/server/middlewares.js',
            templateValues: 'src/server/template-values.js',
            disableProgressbar: true,
            input: {
                web: 'src/shared/client-entry.js',
                node: 'src/server/server-entry.js',
            },
            redux: {
                middlewares: 'src/shared/redux-middlewares.js',
            },
        },
        dev: {
            browsersync: {
                options: {
                    open: false,
                },
            },
            yellowbox: {
                enabled: false,
            },
            redux: {
                devTools: {
                    enabled: false,
                },
                logger: {
                    __raw: {
                        predicate: function(getState, action) {
                            const ignore = ['TICKER_DATA_RECEIVED'];

                            if (ignore.indexOf(action.type) > -1) {
                                return false;
                            }

                            return true;
                        },
                    },
                },
            },
        },
    },
    project: {
        actions: [
            {
                hook: 'build-webpack',
                action: function() {
                    return function(target) {
                        return function(webpackConfig) {
                            if (target === 'web') {
                                webpackConfig.plugins.push(new IgnorePlugin(/unicode\/category\/So/));
                            }
                            return webpackConfig;
                        };
                    };
                },
            },
        ],
    }
};
```

**Comment by dlmr** [comment]
Hello!

When building the application you need to have the development dependencies available, more specifically `roc-package-web-app-react-dev`. So you need to install all dependencies for your application before building, afterwards you can remove the development ones but do note that you will still see this warning but it will work fine. 

[We want to look into managing this better in the future, see this issue for more information about it.](https://github.com/rocjs/roc/issues/120)

**Comment by Visya** [comment]
I think this should be better documented because right now it seems counterintuitive.

Especially taking into account [this part](https://github.com/rocjs/roc/blob/master/docs/Extensions.md#development-extensions) of roc.js documentation:

> For example would a development version of roc-package-web-app be roc-package-web-app-dev. This mainly makes it possible to have the non-development extension in the normal dependencies and the development extension in devDependencies allowing projects to only install what they need for a given situation.

This does not apply for `roc-package-web-app-react` because you have to install the `roc-package-web-app-react-dev` to the dependencies or use a gross hack like

```
NODE_ENV=development npm install
roc build
roc start
```

**Comment by dlmr** [comment]
I don't think that text is presenting the wrong image here, but maybe it can be more clear. To do things like building and running the application in development we need the `devDependencies` and something that is universal for Node projects, like using `webpack` or `babel`.

The normal dependencies are only needed when running, something that hold true here as well but requires us to have built it first.

It's possible to have a "clean" `node_modules` after building by either using `npm prune` or removing `node_modules` and installing again with `npm install --production`.

I also want to note that your `roc.config.js` file will have a problem when running without `devDependencies` since it directly imports `webpack`. You can move the require to the `build-webpack` function and it will work great.

**Comment by Visya** [comment]
Okay, makes sense. Thank you.
